### ISSUE TITLE
How to train on my dataset?

### ISSUE THREAD

**Issue by zxshi** [shahsohil/sunets#7]
Thanks for your share!
I want to konw how to train on my datasets?
My image and label is RGB

**Comment by shahsohil** [comment]
@zxshi Currently the code accepts image in .jpg and labels in .png format. In order to convert labels from RGB to .png format please follow encode_segmap https://github.com/shahsohil/sunets/blob/11057da8adb886c62712a8e0f75f7e9bf10485cf/ptsemseg/loader/pascal_voc_loader.py#L164 and get_pascal_labels https://github.com/shahsohil/sunets/blob/11057da8adb886c62712a8e0f75f7e9bf10485cf/ptsemseg/loader/pascal_voc_loader.py#L158 functions. Note that this converts RGB labels to index. Index can be in any order as far as it is kept same across train and test set. In get_pascal_labels, replace pascal dataset labels with labels from your dataset.

**Comment by zxshi** [comment]
OK, thank you very much!
I will try it.

**Comment by zxshi** [comment]
I noticed that you have used the network to get good results in the land cover classification challenge. Can you share the complete code in this challenge?
